---
# tasks file for ssl-crt

- name: Ensure openssl is installed | RedHat
  yum:
    name: openssl
    state: present
  tags: ssl
  when: ansible_os_family == "RedHat"

- name: Ensure openssl is installed | Debian
  apt:
    name: openssl
    state: present
  tags: ssl
  when: ansible_os_family == "Debian"

- name: Create ssl certificates direcotry
  file:
    path: "{{ ssl_dir }}"
    mode: "0700"
    state: directory
  tags: ssl

- include: rsa.yml
  static: no
  when: not ssl_ecc_crt

- include: ecc.yml
  static: no
  when: ssl_ecc_crt

- name: generate DH param
  command: "openssl dhparam -dsaparam -out {{ ssl_dhparam_file }} {{ ssl_dhparam_size }}"
  args:
    creates: "{{ ssl_dhparam_file }}"
  tags: ssl,dhparam
