---
# tasks file for ssl-crt

- name: Ensure openssl is installed
  yum:
    name: openssl
    state: present
  tags: ssl

- name: Create ssl certificates direcotry
  file:
    path: "{{ ssl_dir }}"
    mode: "0700"
    state: directory
  tags: ssl

- name: Generate ssl key and csr
  command: "openssl req -newkey rsa:{{ ssl_key_size }} -nodes -keyout {{ ssl_key_file }} -out {{ ssl_csr_file}} -subj {{ ssl_csr_subject_fields }}"
  args:
    creates: "{{ item }}"
  with_items:
    - "{{ ssl_key_file }}"
    - "{{ ssl_csr_file }}"
  tags: ssl,csr

- name: Generate self-signed crt
  command: "openssl x509 -signkey {{ ssl_key_file }} -in {{ ssl_csr_file }} -req -days {{ ssl_crt_days }} -sha256 -out {{ ssl_crt_file }}"
  args:
    creates: "{{ ssl_crt_file }}"
  tags: ssl,crt

- name: generate DH param
  command: "openssl dhparam -dsaparam -out {{ ssl_dhparam_file }} {{ ssl_dhparam_size }}"
  args:
    creates: "{{ ssl_dhparam_file }}"
  tags: ssl,dhparam
