---

- name: Generate ssl key and csr
  command: "openssl req -newkey rsa:{{ ssl_key_size }} -nodes -keyout {{ ssl_key_file }} -out {{ ssl_csr_file}} -subj {{ ssl_csr_subject_fields }}"
  args:
    creates: "{{ item }}"
  with_items:
    - "{{ ssl_key_file }}"
    - "{{ ssl_csr_file }}"
  tags: ssl,csr

- name: Generate self-signed crt
  command: "openssl x509 -signkey {{ ssl_key_file }} -in {{ ssl_csr_file }} -req -days {{ ssl_crt_days }} -sha256 -out {{ ssl_crt_file }}"
  args:
    creates: "{{ ssl_crt_file }}"
  tags: ssl,crt
